version: '3.9'
name: restaurant-document-generate-svc

services:
  restaurant-document-generate-svc:
    image: restaurant-document-generate-svc
    networks:
      - project-network
    container_name: restaurant-document-generate-svc
    build:
      dockerfile: ../../build/dockerfile
    ports:
      - "42984:3110"
    environment:
      "APP_ROOT_PATH" : "."
      "OTEL_SERVICE_NAME": "restaurant.document-generate-svc"
      "OTEL_EXPORTER_OTLP_METRICS_ENDPOINT": "otel-collector:4317"

    volumes:
      - ./log/:/app/log/
      - ./run/:/app/run/
      - ./template/:/app/template/
      - ./output/:/app/output/
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    networks:
      - project-network
    container_name: otel-collector
    volumes:
    - ./otel-collector-config.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
networks:
  project-network:
    name: restaurant
    external: true