version: '3.9'
name: restaurant-document-generate-svc

services:
  restaurant-document-generate-svc:
    image: restaurant-document-generate--svc
    networks:
      - project-network
    container_name: restaurant-document-generate-svc
    build:
      dockerfile: ../../build/dockerfile
    ports:
      - "42984:3110"
    volumes:
      - ./log/:/app/log/
      - ./run/:/app/run/
      - ./template/:/app/template/
      - ./output/:/app/output/

networks:
  project-network:
    name: restaurant
    external: true