version: '3.9'
name: restaurant-document-svc

services:
  restaurant-document-svc:
    image: restaurant-document-svc
    networks:
      - dev-net
    container_name: restaurant-document-svc
    build:
      dockerfile: ../../build/dockerfile
    volumes:
      - ./log/:/app/log/
      - ./run/:/app/run/
      - ./template/:/app/template/

networks:
  dev-net:
    name: restaurant-dev-net
    external: true