version: '3.9'
name: restaurant-generate-document-svc

services:
  restaurant-generate-document-svc:
    image: restaurant-generate-document-svc
    networks:
      - dev-net
    container_name: restaurant-generate-document-svc
    build:
      dockerfile: ../../build/dockerfile
    ports:
      - "3110:3110"
    volumes:
      - ./log/:/app/log/
      - ./run/:/app/run/
      - ./template/:/app/template/
      - ./output/:/app/output/

networks:
  dev-net:
    name: restaurant-dev-net
    external: true